name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: branch@master
    - name: test
      run: |
        xmake build -y test
        xmake run test
    - name: artifact
      run: |
        xmake -y
        xmake install -o build/luject
        cd build/luject
        zip luject-${{matrix.os}}.zip -r .
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: build/luject/luject-${{matrix.os}}.zip
